version: 0.2
phases:
  pre_build:
    commands:
      - echo "starting build process...."
  build:
    commands:
      - echo "copying DAG files to s3...."
      - aws s3 cp --recursive ./dags s3://airflow-managed-gds11/dags/
      - echo "Copying dim data files to S3..."
      - aws s3 cp --recursive ./data_for_dim s3://food-delivery-data-analysis/dims/
      - echo "Copying pyspark scripts to S3..."
      - aws s3 cp --recursive ./scripts s3://food-delivery-data-analysis/pyspark_script/
      - echo "Copying redshift jar file to S3..."
      - aws s3 cp --recursive ./jars s3://food-delivery-data-analysis/redshift-connector-jar/
  post_build:
    commands:
      - echo "Build and deployment process complete!!!"